

services:
  web:
    build: .
    command: >
      /app/wait-for-it.sh db:5432 --timeout=30 --
      python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      POSTGRES_DB: growthflow_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin2310
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_DB: growthflow_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin2310

volumes:
  postgres_data: